apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lington-puffy-dev
  namespace: argocd

  annotations:
    # Track this image (alias = app)
    argocd-image-updater.argoproj.io/image-list: 468887949677.dkr.ecr.eu-west-3.amazonaws.com/lington-puffy-app1

    # Auto-update tags using semver
    argocd-image-updater.argoproj.io/app.update-strategy: semver

    # Only match tags like 99.99.xxx
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^99\.99\.\d+$
    argocd-image-updater.argoproj.io/write-back-method: git    # Commit back to Git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/mr-lington/Argocd-GitOps.git
    targetRevision: HEAD
    path: overlays/dev
    kustomize: {}       

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
